//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int SeatId { get; set; }
        public string Column { get; set; }
        public Nullable<int> ColumnNumber { get; set; }
        public int OperationId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Operation Operation { get; set; }
    }
}
